# Generated by Django 3.2 on 2021-04-28 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_gusto', '0003_adress_cafeinfo_info_message_openinghours_phone_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='dish',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='slug',
            field=models.SlugField(default='food'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='title',
            field=models.CharField(db_index=True, max_length=25, unique=True),
        ),
        migrations.AlterIndexTogether(
            name='dish',
            index_together={('id', 'slug')},
        ),
    ]
